kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 1Gi
      retention: 6h
      storageSpec: {}

  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          memory: 128Mi

  grafana:
    adminPassword: admin
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        label: grafana_dashboard
        labelValue: "1"

  prometheus-node-exporter:
    resources:
      requests:
        cpu: 25m
        memory: 32Mi

  kube-state-metrics:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
