apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: training-cluster-queue
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1" # after resource-flavors.yaml (weight 0), which it references by name
spec:
  namespaceSelector: {} # match all namespaces
  resourceGroups:
    - coveredResources: ["cpu", "memory"]
      flavors:
        - name: default-flavor
          resources:
            - name: "cpu"
              nominalQuota: {{ .Values.queue.cpu.nominalQuota | quote }}
            - name: "memory"
              nominalQuota: {{ .Values.queue.memory.nominalQuota | quote }}
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: gpu-flavor
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: {{ .Values.queue.gpu.nominalQuota | quote }}
