apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-seaweedfs-auth-config
type: Opaque
stringData:
  seaweedfs_s3_config: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "{{ .Values.secrets.s3AccessKey }}",
              "secretKey": "{{ .Values.secrets.s3SecretKey }}"
            }
          ],
          "actions": ["Read", "Write", "List", "Tagging", "Admin"]
        }
      ]
    }