apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-unified-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.dbPassword }}

  # SeaweedFS / S3 Keys
  s3-access-key: {{ .Values.secrets.s3AccessKey }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey }}