apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ENVIRONMENT: {{ .Values.env.environment | quote }}
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ printf "%s-redis" .Release.Name | quote }}
  {{- else }}
  REDIS_HOST: {{ .Values.env.redisHost | quote }}
  {{- end }}
  REDIS_PORT: {{ .Values.env.redisPort | quote }}
  ML_FLOW_URI: {{ .Values.env.mlflowUri | quote }}
  {{- if .Values.env.s3Endpoint }}
  S3_ENDPOINT: {{ .Values.env.s3Endpoint | quote }}
  {{- end }}
  K8S_NAMESPACE: {{ .Values.env.k8sNamespace | quote }}
  TRAINING_JOB_SERVICE_ACCOUNT: {{ .Values.env.trainingJobServiceAccount | quote }}
  DEFAULT_JOB_DEADLINE_SECONDS: {{ .Values.env.defaultJobDeadlineSeconds | quote }}
  ZOMBIE_JOB_MAX_AGE_SECONDS: {{ .Values.env.zombieJobMaxAgeSeconds | quote }}
