apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-zombie-disposer
spec:
  schedule: {{ .Values.zombieDisposerCronSchedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.orchestrator.name }}
          restartPolicy: Never
          containers:
            - name: zombie-disposer
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python", "-m", "app.security.zombie_process_disposer"]
              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}-config
                - secretRef:
                    name: {{ .Release.Name }}-secrets
