apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
