apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- if .Values.env.s3Endpoint }}
  AWS_KEY: {{ .Values.secrets.awsKey | quote }}
  AWS_SECRET: {{ .Values.secrets.awsSecret | quote }}
  {{- end }}
