apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.orchestrator.name }}
  {{- if .Values.serviceAccount.orchestrator.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.orchestrator.irsaRoleArn }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.trainingJob.name }}
  {{- if .Values.serviceAccount.trainingJob.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.trainingJob.irsaRoleArn }}
  {{- end }}
